# Stage 1: Build
FROM maven:3.9-eclipse-temurin-21-alpine AS build
WORKDIR /app
COPY pom.xml .
COPY src ./src
RUN mvn clean package -DskipTests

# Stage 2: Run
FROM eclipse-temurin:21-jre-alpine
WORKDIR /app
COPY --from=build /app/target/skillservice-0.0.1-SNAPSHOT.jar .
ENTRYPOINT ["java", "-jar", "skillservice-0.0.1-SNAPSHOT.jar"]
